apiVersion: v1
kind: Service
metadata:
  name: ldap-service
spec:
  selector:
    app.kubernetes.io/name: ldap
  ports:
    - protocol: TCP
      port: 389
      targetPort: ldap
      name: ldap
    - protocol: TCP
      port: 636
      targetPort: ldaps
      name: ldaps