global:
  imagePullSecrets:
    - name: "cgrcred"
installCRDs: true
image:
  repository: cgr.dev/chainguard-private/cert-manager-controller
  tag: latest-dev
cainjector:
  image:
    repository: cgr.dev/chainguard-private/cert-manager-cainjector
    tag: latest-dev
acmesolver:
  image:
    repository: cgr.dev/chainguard-private/cert-manager-acmesolver
    tag: latest-dev
webhook:
  image:
    repository: cgr.dev/chainguard-private/cert-manager-webhook
    tag: latest-dev